- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Create custom index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

- name: Restart Nginx
  service:
    name: nginx
    state: restarted